import React, { FC, Key } from 'react'
import Head from 'next/head'
import { GetStaticProps } from 'next'
import axios from 'axios'
import { useSelector, useDispatch } from 'react-redux'
import { updatePortfolio } from '@/context/actions'
import { Intro, WordCloud, ScreenLayout, Carousel, ProjectCard, ExperienceCard, EducationCard, Timeline } from '@/components'

import Portfolio from "utils/types"
import Image from 'next/image'

const Home: FC <Portfolio> = (props) => {
  // const portfolio = useSelector((state: any) => state.portfolio)
  // const { skills, projects, experience, education } = portfolio;
  // const dispatch = useDispatch()

  // if(props?.data) dispatch(updatePortfolio(props.data))
  const { username, fullname, about, email, images, roles, skills, links, projects, experience, education } = props;

  return (
    <>
      <Head>
        <title>DevPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        {/* Intro */}
        <ScreenLayout>
          <Intro links={links} fullname={fullname} about={about} images={images} roles={roles} />
        </ScreenLayout>

        {/* Skills */}
        <ScreenLayout>
          <WordCloud skills={skills}/>
        </ScreenLayout>

        <ScreenLayout>
          <Timeline experience={experience} education={education} />
        </ScreenLayout>

        {/* Projects */}
        <ScreenLayout>
          <Carousel slides={projects} options={{ loop: false }}/>
        </ScreenLayout>

        {/* <ScreenLayout>
            {projects.map((project, index: Key) => (
              <div key={index} className="flex-shrink-0 flex-grow-0 basis-full min-w-0 bg-white/20">
                <ProjectCard project={project} />
              </div>
            ))}
        </ScreenLayout> */}


        {/* Experience */}
        <ScreenLayout>
          {experience.map((experience, index: Key) => (
            <ExperienceCard key={index} experience={experience} />
          ))}
        </ScreenLayout>

        {/* Education */}
        <ScreenLayout>
          {education.map((education, index: Key) => (
            <EducationCard key={index} education={education} />
          ))}
        </ScreenLayout>
      </main>
    </>
  )
}

export default Home;


// SSG 
export async function getStaticProps() {
  // const url = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3001';
  const url = process.env.BASE_URL;
  const res = await axios.get(`${url}/api/prashantamoli`)
  const data = await res.data
  return {
    props: data
  }
}
